# Generated by Django 3.0.4 on 2020-05-17 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('file', models.FileField(null=True, upload_to='files')),
                ('content', models.TextField(null=True)),
                ('date_created', models.DateTimeField()),
                ('kind', models.CharField(choices=[('vid', 'Video'), ('pic', 'Picture'), ('aud', 'Audio'), ('text', 'Text')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField()),
                ('is_draft', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('correct', models.CharField(choices=[('answer_1', 'answer_1'), ('answer_2', 'answer_2'), ('answer_3', 'answer_3'), ('answer_4', 'answer_4')], default=False, max_length=10, verbose_name='Correct answer')),
                ('answer_1', models.CharField(max_length=255, null=True, verbose_name='Answer')),
                ('answer_2', models.CharField(max_length=255, null=True, verbose_name='Answer')),
                ('answer_3', models.CharField(max_length=255, null=True, verbose_name='Answer')),
                ('answer_4', models.CharField(max_length=255, null=True, verbose_name='Answer')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adaptivevle.Quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='UserMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adaptivevle.Material')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField()),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adaptivevle.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizquestion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adaptivevle.QuizQuestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adaptivevle.Topic'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('S', 'Student'), ('T', 'Teacher')], max_length=7)),
                ('learning_style', models.CharField(choices=[('V', 'Visual'), ('A', 'Aural'), ('R', 'Read/Write'), ('K', 'Kinesthetic'), ('M', 'Multimodal')], default=None, max_length=1, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adaptivevle.Topic'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_created', models.DateTimeField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adaptivevle.Material')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
    ]
