# Generated by Django 3.0.4 on 2020-05-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptivevle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='quizanswer',
            field=models.CharField(choices=[('answer_1', 'answer_1'), ('answer_2', 'answer_2'), ('answer_3', 'answer_3'), ('answer_4', 'answer_4')], default=None, max_length=10, verbose_name='Answer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='correct',
            field=models.CharField(choices=[('answer_1', 'answer_1'), ('answer_2', 'answer_2'), ('answer_3', 'answer_3'), ('answer_4', 'answer_4')], max_length=10, verbose_name='Correct answer'),
        ),
    ]
