# Generated by Django 3.0.4 on 2020-05-26 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adaptivevle', '0002_auto_20200517_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'quizes'},
        ),
    ]
