# Generated by Django 3.0.4 on 2020-05-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptivevle', '0003_auto_20200526_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='kind',
            field=models.CharField(choices=[('vid', 'Video'), ('pic', 'Picture'), ('aud', 'Audio'), ('text', 'Text'), ('presentation', 'Presentation')], max_length=12),
        ),
    ]
